export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_BY_ID_REQ = 'USER_BY_ID_REQ';
export const USER_BY_ID_SUC = 'USER_BY_ID_SUC';
export const USER_BY_ID_FAI = 'USER_BY_ID_FAI';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_CREATE_ACT_REQ = 'USER_CREATE_ACT_REQ';
export const USER_CREATE_ACT_SUC = 'USER_CREATE_ACT_SUC';
export const USER_CREATE_ACT_FAIL = 'USER_CREATE_ACT_FAI';
export const USER_CREATE_ACT_RES = 'USER_CREATE_ACT_RES';

export const GET_ACTION_REQ = 'GET_ACTION_REQ';
export const GET_ACTION_SUC = 'GET_ACTION_SUC';
export const GET_ACTION_FAI = 'GET_ACTION_FAI';
export const GET_ACTION_RES = 'GET_ACTION_RES';

export const LANDOWNER_LIST_REQ = 'LANDOWNER_LIST_REQ';
export const LANDOWNER_LIST_SUC = 'LANDOWNER_LIST_SUC';
export const LANDOWNER_LIST_FAI = 'LANDOWNER_LIST_FAI';
export const LANDOWNER_LIST_RES = 'LANDOWNER_LIST_RES';

export const LANDOWNER_BY_ID_REQ = 'LANDOWNER_BY_ID_REQ';
export const LANDOWNER_BY_ID_SUC = 'LANDOWNER_BY_ID_SUC';
export const LANDOWNER_BY_ID_FAI = 'LANDOWNER_BY_ID_FAI';
export const LANDOWNER_BY_ID_RES = 'LANDOWNER_BY_ID_RES';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const CREATE_DELETE_USER = 'CREATE_DELETE_USER';
export const CREATE_NEW_LAND = 'CREATE_NEW_LAND';
export const SALE_LAND = 'SALE_LAND';
export const UPDATE_LAND = 'UPDATE_LAND';

export const LOCK_REQ = 'LOCK_REQ';
export const LOCK_SUC = 'LOCK_SUC';
export const LOCK_FAI = 'LOCK_FAI';

export const USER_T_LIST_REQ = 'USER_T_LIST_REQ';
export const USER_T_LIST_SUC = 'USER_T_LIST_SUC';
export const USER_T_LIST_FAI = 'USER_T_LIST_FAI';

export const USER_T_CREATE_REQ = 'USER_T_CREATE_REQ';
export const USER_T_CREATE_SUC = 'USER_T_CREATE_SUC';
export const USER_T_CREATE_FAI = 'USER_T_CREATE_FAI';

export const USER_T_DEL_REQ = 'USER_T_DEL_REQ';
export const USER_T_DEL_SUC = 'USER_T_DEL_SUC';
export const USER_T_DEL_FAI = 'USER_T_DEL_FAI';

export const USER_T_UPDATE_REQ = 'USER_T_UPDATE_REQ';
export const USER_T_UPDATE_SUC = 'USER_T_UPDATE_SUC';
export const USER_T_UPDATE_FAI = 'USER_T_UPDATE_FAI';

export const USER_T_BY_ID_REQ = 'USER_T_BY_ID_REQ';
export const USER_T_BY_ID_SUC = 'USER_T_BY_ID_SUC';
export const USER_T_BY_ID_FAI = 'USER_T_BY_ID_FAI';
