export const LAND_LIST_REQ = 'LAND_LIST_REQ';
export const LAND_LIST_SUC = 'LAND_LIST_SUC';
export const LAND_LIST_FAI = 'LAND_LIST_FAI';

export const LAND_CREATE_REQ = 'LAND_CREATE_REQ';
export const LAND_CREATE_SUC = 'LAND_CREATE_SUC';
export const LAND_CREATE_FAI = 'LAND_CREATE_FAI';
export const LAND_CREATE_RES = 'LAND_CREATE_RES';
